[workspace]
resolver = "2"
members = ["type_flyweight" ]

[workspace.dependencies]
rusqlite = { version = "0.32" }
snowprints = { git = "https://github.com/taylor-vann/snowprints", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"